name: Enviar dados
description: Formulário para coletar informações
title: "[Formulário] {{ inputs.nome }}"
labels: [formulario]
body:
  - type: input
    id: nome
    attributes:
      label: Nome
      description: Seu nome completo
      placeholder: João da Silva
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: E-mail
      description: Para contato
      placeholder: exemplo@email.com
    validations:
      required: true

  - type: textarea
    id: mensagem
    attributes:
      label: Mensagem
      description: Escreva sua mensagem aqui
      placeholder: Digite aqui...
    validations:
      required: true
